name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'Github Issues'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const item = github.context.payload.issue || github.context.payload.pull_request;
            if (!item) {
              console.log('No issue or pull request found in the context');
              return;
            }
            const labels = item.labels.map(label => label.name);
            
            let assignee = 'Teemsploit';
            
            if (labels.includes('frontend')) {
              assignee = 'indexxing';
            } else if (labels.includes('backend')) {
              assignee = 'TeemSucks';
            }
          
            await github.rest.issues.addAssignees({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: item.number,
              assignees: [assignee]
            });
