name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'GitHub Issues Auto-Assign'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const item = context.payload.issue || context.payload.pull_request;
            
            if (!item) {
              console.log("No issue or pull request found in the context. Exiting.");
              return;
            }

            console.log("Issue/PR Found:", JSON.stringify(item, null, 2));

            const labels = item.labels ? item.labels.map(label => label.name) : [];
            
            let assignee = 'Teemsploit';
            
            if (labels.includes('frontend')) {
              assignee = 'indexxing';
            } else if (labels.includes('backend')) {
              assignee = 'TeemSucks';
            }

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: item.number,
              assignees: [assignee]
            });
