name: Server Status

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Server Status
        run: |
          if curl -Is https://bipbop.bopimod.com | head -n 1 | grep "200"; then
            exit 0
          else
            exit 1
          fi
